server:
  port: 8080
  



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hikeon
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@1998
 
 
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: create-drop